### ISSUE TITLE
LG 22EA63

### ISSUE THREAD

**Issue by rusikf** [ddccontrol/ddccontrol-db#92]
Hi guys, Can you please add support to LG 22EA63 ? It has support DDC ( https://www.lg.com/ru/monitors/lg-22EA63V-ips-monitors)

```
pi@raspberrypi:~ $ sudo gddccontrol
I/O warning : failed to load external entity "/root/.ddccontrol/monitorlist"
Document not parsed successfully.
Probing for available monitors

pi@raspberrypi:~ $ sudo ddccontrol -p
ddccontrol version 0.4.4
Copyright 2004-2005 Oleg I. Vdovikin (oleg@cs.msu.su)
Copyright 2004-2006 Nicolas Boichat (nicolas@boichat.ch)
This program comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of this program under the terms of the GNU General Public License.

Probing for available monitors
Detected monitors :
No monitor supporting DDC/CI available.
If your graphics card need it, please check all the required kernel modules are loaded (i2c-dev, and your framebuffer driver).

```

**Comment by kravemir** [comment]
Hello @rusikf, what graphics card do you have? There are some DDC issues with nvidia cards/drivers.

**Comment by rusikf** [comment]
Hi, thanks for fast response !I dont have above of them.I have raspberry pi
4, which dont have external video card.

**Comment by larstobi** [comment]
I don't have a Raspberry Pi 4, but it looks like this is not supported by the board. See https://github.com/raspberrypi/linux/issues/3152 

I'm closing this one until that one is resolved.
