### ISSUE TITLE
README does not mention how to create new entries

### ISSUE THREAD

**Issue by hackerb9** [ddccontrol/ddccontrol-db#94]
The README mentions how to use ddccontrol, but not what to do if one's monitor is not in the database. I'd like to create an entry for my monitor (SAM0C3F.xml) but it's not clear what I should do next. If there is documentation somewhere, please link to it from the README.md file. If there isn't, please add some. Thanks!

**Comment by kravemir** [comment]
@hackerb9, thank you for notice. The project (README.md) misses contributing section, which would navigate potential contributors to some documentation.

Even thought, database is not complex, and can be studied and a bit reverse-engineered, ..  you're right, that it's not clear what contributors should do. And, some checklist, guide, or documentation, would be much straightforward and convenient process.

I'll create/link something in future. For now, to create `SAM0C3F.xml` you can get inspired by other samsung monitors. The most of the configurations extend vesa config, which covers lots of basic options, and vendor-specific options are added on top of that (in xml, preceeding include of VESA).

For example:

- simple one: https://github.com/ddccontrol/ddccontrol-db/commit/0cda38bdda3dfd959c31be2756f9409db012735c
- more complex one: https://github.com/ddccontrol/ddccontrol-db/commit/d294da1f7ec6dd0fc58ba3fdc446a2bbb5ff80f4

Sorry for not showing contributors a convenient way to do it, yet.
