### ISSUE TITLE
Samsung C49RG90S (C49R series)

### ISSUE THREAD

**Issue by perara** [ddccontrol/ddccontrol-db#98]
LANG= LC_ALL= ddccontrol -p -c -d
ddccontrol version 0.4.5-unreleased
Copyright 2004-2005 Oleg I. Vdovikin (oleg@cs.msu.su)
Copyright 2004-2006 Nicolas Boichat (nicolas@boichat.ch)
This program comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of this program under the terms of the GNU General Public License.

Detected monitors :
 - Device: dev:/dev/i2c-7
   DDC/CI supported: Yes
   Monitor Name: Samsung standard LCD
   Input type: Digital
  (Automatically selected)
 - Device: dev:/dev/i2c-4
   DDC/CI supported: Yes
   Monitor Name: Samsung standard LCD
   Input type: Digital
Reading EDID and initializing DDC/CI at bus dev:/dev/i2c-7...
I/O warning : failed to load external entity "/usr/share/ddccontrol-db/monitor/SAM0F9C.xml"
Document not parsed successfully.

EDID readings:
	Plug and Play ID: SAM0F9C [Samsung standard LCD]
	Input type: Analog
=============================== WARNING ===============================
There is no support for your monitor in the database, but ddccontrol is
using a generic profile for your monitor's manufacturer. Some controls
may not be supported, or may not work as expected.
Please update ddccontrol-db, or, if you are already using the latest
version, please send the output of the following command to
ddccontrol-users@lists.sourceforge.net:

LANG= LC_ALL= ddccontrol -p -c -d

Thank you.
=============================== WARNING ===============================

Capabilities:
ioctl(): Inappropriate ioctl for device
ioctl returned -1
ioctl(): Inappropriate ioctl for device
ioctl returned -1
ioctl(): Inappropriate ioctl for device
ioctl returned -1
ioctl(): Inappropriate ioctl for device
ioctl returned -1
ioctl(): Inappropriate ioctl for device
ioctl returned -1
ioctl(): Inappropriate ioctl for device
ioctl returned -1
ioctl(): Inappropriate ioctl for device
ioctl returned -1
ioctl(): Inappropriate ioctl for device
ioctl returned -1
ioctl(): Inappropriate ioctl for device
ioctl returned -1
Capabilities read fail.

Controls (valid/current/max) [Description - Value name]:
Control 0x02: +/1/2 C [Secondary Degauss - Secondary Degauss]
Control 0x08: +/0/0 C [Restore Factory Default Color]
Control 0x10: +/100/100 C [Brightness]
Control 0x12: +/75/100 C [Contrast]
Control 0x14: +/2/5 C [???]
Control 0x16: +/50/100 C [Red maximum level]
Control 0x18: +/50/100 C [Green maximum level]
Control 0x1a: +/50/100 C [Blue maximum level]
Control 0x20: +/0/255   [???]
Control 0x30: +/0/255   [???]
Control 0x60: +/9/14 C [Input Source Select (Main)]
Control 0x87: +/15/100   [???]
Control 0xaa: +/1/3 C [OSD Orientation - Landscape]
Control 0xb0: +/0/255   [???]
Control 0xb6: +/3/9 C [???]
Control 0xc6: +/1/1 C [???]
Control 0xc8: +/5/16 C [???]
Control 0xc9: +/1/1 C [???]
Control 0xca: +/2/2   [???]
Control 0xcc: +/2/30   [???]
Control 0xd6: +/0/255 C [DPMS Control]
Control 0xdb: +/0/255   [???]
Control 0xdc: +/24/3 C [Magic Bright Mode]
Control 0xdf: +/512/514 C [???]
Control 0xe0: +/2/5   [???]
Control 0xe1: +/2/5 C [Power control]
Control 0xe2: +/2/5   [???]
Control 0xe5: +/0/1   [???]
Control 0xe6: +/0/1   [???]
Control 0xe9: +/0/255   [???]
Control 0xf3: +/0/2   [???]
Control 0xf5: +/0/255   [???]
Control 0xf7: +/0/3   [???]
Control 0xfe: +/1/2   [???]

**Comment by sentiasa** [comment]
I have a use-case: when I need to screenshare, I need to change my resolution to 16:9. 
Toggle between from Menu > Game > Screen Size > 27" Wide (16:9) & Wide.

I checked the xml @solarkennedy added - it only includes language, response time and input source. 
Is it possible to add the screen size changes as well?

Unfortunately, I don't know about how to read these so I can't contribute, but if not a big effort for you, can you please add it? Or if you can guide me, I'd be happy to add them.

**Comment by solarkennedy** [comment]
I can confirm by checking readings before and after that the "Screen Size"
setting is _not_ exported as a control.
